name: nahed_azkar
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  flutter_localizations:
    sdk: flutter
  intl: 0.18.0
  cupertino_icons: ^1.0.2
  hijri: ^3.0.0
  audioplayers: ^1.1.0
  share_plus: ^6.3.0
  flutter_bloc: ^8.1.3
  quran: ^1.2.2
  curved_navigation_bar: ^1.0.3
  adhan_dart: ^1.0.8
  geolocator: ^9.0.2
  adhan: ^2.0.0-nullsafety.2
  flutter_qiblah:
  flutter_svg: ^1.1.5
  url_launcher: ^6.1.11
  flutter_colorpicker: ^1.0.3
  shared_preferences: ^2.1.2
  flutter_islamic_icons: ^1.0.2
  flutter_local_notifications: ^15.1.0+1
  path: ^1.8.3
  path_provider: ^2.0.15
  sqflite: ^2.3.0
  timezone: ^0.9.2
  media_cache_manager:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/sound_button.mp3
  #   - images/a_dot_ham.jpeg
  # example:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/font/MyFlutterApp.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
