name: nahed_azkar
description: A new Flutter project.
publish_to: 'none'
version: 2.0.14+14

environment:
  sdk: '>=3.5.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  hijri: ^3.0.0
  audioplayers: ^6.1.0
  share_plus: ^10.1.1
  flutter_bloc: ^8.1.6
  quran:
  curved_navigation_bar: ^1.0.6
  adhan_dart: ^1.1.2
  geolocator: ^13.0.1
  adhan: ^2.0.0+1
  flutter_qiblah: ^3.0.4
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.1
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.3.2
  flutter_islamic_icons: ^1.0.2
  flutter_local_notifications: 18.0.1
  path: ^1.9.0
  path_provider: ^2.1.4
  sqflite: ^2.4.0
  timezone: ^0.9.4
  media_cache_manager: ^0.2.2
  http: ^1.2.2
  connectivity_plus: ^6.1.0
  google_fonts: ^6.2.1
  permission_handler:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/sound_button.mp3
  #   - images/a_dot_ham.jpeg
  # example:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/font/MyFlutterApp.ttf

    - family: uthmanic
      fonts:
        - asset: assets/font/uthmanic_hafs_v20.ttf
    - family: ggess
      fonts:
        - asset: assets/font/GE_SS_Two_Bold.otf
    - family: amiri
      fonts:
        - asset: assets/font/Amiri.ttf
    - family: diwan
      fonts:
        - asset: assets/font/diwan.ttf
    - family: kufi
      fonts:
        - asset: assets/font/kofi.ttf
    - family: thulth
      fonts:
        - asset: assets/font/Thulth-Bold.ttf
